#!/usr/bin/bash


export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export PATH="$HOME/.local/bin:$PATH" # PATH

## History stuffs
export HISTCONTROL=ignoredups # ignore duplicates in history
export HISTSIZE=1000 # Increase history size 

shopt -s autocd #auto cd

# DEFAULT PROGRAMS
export EDITOR='nvim'
export TERMINAL='konsole'
export BROWSER='thorium'
export MANPAGER='batman'

# HOME 
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
